name: 'Compute coverage stats'
description: 'Compute coverage stats based on lcov file'
inputs:
  coverage-file:
    description: 'token to write to the gist'
    required: true
outputs:
  coverage:
    description: 'coverage stats'

  coverage-color:
    description: 'coverage color'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.coverage-file }}
