on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test action
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: run test
        run: |
          cd test
          for test in test-*.bats; do 
            ./$test
          done
